import { ToolOption } from "@/store/pipeline";

export const TOOLS_BY_STEP: Record<string, ToolOption[]> = {
  "01-titles": [
    {
      id: "claude-sonnet",
      name: "Claude Sonnet",
      tier: "paid",
      costPerUse: "~$0.002/call",
      commercialOk: true,
      quality: 3,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "ANTHROPIC_API_KEY",
    },
    {
      id: "chatgpt-free",
      name: "ChatGPT 3.5 (web)",
      tier: "free",
      costPerUse: "$0",
      commercialOk: true,
      quality: 2,
      speed: "medium",
      requiresManual: true,
      apiSupported: false,
    },
  ],
  "02-lyrics": [
    {
      id: "claude-sonnet",
      name: "Claude Sonnet",
      tier: "paid",
      costPerUse: "~$0.005/call",
      commercialOk: true,
      quality: 3,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "ANTHROPIC_API_KEY",
    },
    {
      id: "chatgpt-free",
      name: "ChatGPT 3.5 (web)",
      tier: "free",
      costPerUse: "$0",
      commercialOk: true,
      quality: 2,
      speed: "medium",
      requiresManual: true,
      apiSupported: false,
    },
  ],
  "03-music-style": [
    {
      id: "claude-sonnet",
      name: "Claude Sonnet",
      tier: "paid",
      costPerUse: "~$0.002/call",
      commercialOk: true,
      quality: 3,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "ANTHROPIC_API_KEY",
    },
  ],
  "04-music-gen": [
    {
      id: "suno-pro",
      name: "Suno Pro",
      tier: "paid",
      costPerUse: "Included",
      monthlyPlan: "Suno Pro $8/mo",
      commercialOk: true,
      quality: 3,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "SUNO_API_KEY",
    },
    {
      id: "udio-pro",
      name: "Udio Pro",
      tier: "paid",
      costPerUse: "Included",
      monthlyPlan: "Udio Pro $10/mo",
      commercialOk: true,
      quality: 3,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "UDIO_API_KEY",
    },
    {
      id: "suno-free",
      name: "Suno Free",
      tier: "free",
      costPerUse: "$0 (50 credits/day)",
      commercialOk: false,
      quality: 2,
      speed: "medium",
      requiresManual: true,
      apiSupported: false,
    },
  ],
  "05-character": [
    {
      id: "dalle3",
      name: "DALL-E 3",
      tier: "paid",
      costPerUse: "$0.04/image",
      commercialOk: true,
      quality: 3,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "OPENAI_API_KEY",
    },
    {
      id: "stability",
      name: "Stability AI",
      tier: "paid",
      costPerUse: "$0.02/image",
      commercialOk: true,
      quality: 2,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "STABILITY_API_KEY",
    },
    {
      id: "ideogram",
      name: "Ideogram",
      tier: "free",
      costPerUse: "$0 (10/day)",
      commercialOk: true,
      quality: 2,
      speed: "slow",
      requiresManual: true,
      apiSupported: false,
    },
  ],
  "06-scenes": [
    {
      id: "dalle3",
      name: "DALL-E 3",
      tier: "paid",
      costPerUse: "$0.04/image",
      commercialOk: true,
      quality: 3,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "OPENAI_API_KEY",
    },
    {
      id: "stability",
      name: "Stability AI",
      tier: "paid",
      costPerUse: "$0.02/image",
      commercialOk: true,
      quality: 2,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "STABILITY_API_KEY",
    },
    {
      id: "ideogram-free",
      name: "Ideogram Free",
      tier: "free",
      costPerUse: "$0 (10/day)",
      commercialOk: true,
      quality: 2,
      speed: "slow",
      requiresManual: true,
      apiSupported: false,
    },
  ],
  "07-animation": [
    {
      id: "kling-pro",
      name: "Kling AI",
      tier: "paid",
      costPerUse: "Included",
      monthlyPlan: "Kling $8/mo",
      commercialOk: true,
      quality: 3,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "KLING_API_KEY",
    },
    {
      id: "runwayml",
      name: "RunwayML Gen-3",
      tier: "paid",
      costPerUse: "Included",
      monthlyPlan: "Runway $15/mo",
      commercialOk: true,
      quality: 3,
      speed: "medium",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "RUNWAY_API_KEY",
    },
    {
      id: "pika-free",
      name: "Pika Labs Free",
      tier: "free",
      costPerUse: "$0 (limited)",
      commercialOk: false,
      quality: 2,
      speed: "slow",
      requiresManual: true,
      apiSupported: false,
    },
  ],
  "08-assembly": [
    {
      id: "ffmpeg",
      name: "FFmpeg (local)",
      tier: "free",
      costPerUse: "$0",
      commercialOk: true,
      quality: 3,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
    },
    {
      id: "creatomate",
      name: "Creatomate",
      tier: "paid",
      costPerUse: "Included",
      monthlyPlan: "Creatomate $29/mo",
      commercialOk: true,
      quality: 3,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "CREATOMATE_API_KEY",
    },
  ],
  "09-youtube": [
    {
      id: "claude-sonnet",
      name: "Claude Sonnet",
      tier: "paid",
      costPerUse: "~$0.003/call",
      commercialOk: true,
      quality: 3,
      speed: "fast",
      requiresManual: false,
      apiSupported: true,
      credentialKey: "ANTHROPIC_API_KEY",
    },
  ],
};
